### ISSUE TITLE
Предложение для /user

### ISSUE THREAD

**Issue by kel-cu** [ReWorlds/TelegramBot#2]
В графе где пишет "В игре: сколько там то времени", сделать так, чтобы при 0сек. или последний вход: неизвестно. Либо не писал эту графу, либо вместо 0сек. ставить "Не играл"
![IMG_20230327_224356.jpg](https://user-images.githubusercontent.com/86980879/228051241-a8ec5b59-23b2-4730-8d24-e8138b63802b.jpg)

**Comment by Statuxia** [comment]
Так как это тоже информация, а её отсутствие противоречит задумке бота - предоставить информацию, я решил оставить данные поля. Но за счет обращения внимания к этой части кода, теперь не выводит лишний раз ноль. [commit](https://github.com/ReWorlds/TelegramBot/commit/05b4f6186f645533fa2c23e9a5736ce5b58e97cb)
